        protected void assertCommitted() throws Exception
        {
            assertPrepared();
        }

